color0 #131314
color1 #ffb4ab
color2 #bec7db
color3 #c4c6cf
color4 #d9bfd2
color5 #bec7db
color6 #c4c6cf
color7 #e4e2e3
color8 #8f9097
color9 #ffb4ab
color10 #bec7db
color11 #c4c6cf
color12 #d9bfd2
color13 #bec7db
color14 #c4c6cf
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c5c6cd
selection_background  #45474c
active_border_color   #bec7db
inactive_border_color #45474c
url_color             #bec7db

active_tab_foreground   #283141
active_tab_background   #bec7db
inactive_tab_foreground #c5c6cd
inactive_tab_background #45474c
cursor_trail_color      #c5c6cd
